package com.karl.entity;

public class College {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.caddress
     *
     * @mbg.generated
     */
    private String caddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.createtime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.cpic
     *
     * @mbg.generated
     */
    private String cpic;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated
     */
    public College(Integer cid, String cname, String caddress, String createtime, String cpic) {
        this.cid = cid;
        this.cname = cname;
        this.caddress = caddress;
        this.createtime = createtime;
        this.cpic = cpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated
     */
    public College() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.cid
     *
     * @return the value of college.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.cid
     *
     * @param cid the value for college.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.cname
     *
     * @return the value of college.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.cname
     *
     * @param cname the value for college.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.caddress
     *
     * @return the value of college.caddress
     *
     * @mbg.generated
     */
    public String getCaddress() {
        return caddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.caddress
     *
     * @param caddress the value for college.caddress
     *
     * @mbg.generated
     */
    public void setCaddress(String caddress) {
        this.caddress = caddress == null ? null : caddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.createtime
     *
     * @return the value of college.createtime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.createtime
     *
     * @param createtime the value for college.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.cpic
     *
     * @return the value of college.cpic
     *
     * @mbg.generated
     */
    public String getCpic() {
        return cpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.cpic
     *
     * @param cpic the value for college.cpic
     *
     * @mbg.generated
     */
    public void setCpic(String cpic) {
        this.cpic = cpic == null ? null : cpic.trim();
    }
}